ln -s ~/.dotfiles/arch/fontconfig ~/.config/fontconfig
ln -s ~/.dotfiles/arch/firefox ~/.config/firefox
ln -s ~/.dotfiles/arch/gtk-3.0 ~/.config/gtk-3.0
ln -s ~/.dotfiles/arch/hypr ~/.config/hypr
ln -s ~/.dotfiles/arch/kitty ~/.config/kitty
ln -s ~/.dotfiles/arch/neofetch ~/.config/neofetch
ln -s ~/.dotfiles/nvim ~/.config/nvim
ln -s ~/.dotfiles/arch/rofi ~/.config/rofi
ln -s ~/.dotfiles/arch/swaylock ~/.config/swaylock
ln -s ~/.dotfiles/arch/swaync ~/.config/swaync
ln -s ~/.dotfiles/arch/waybar ~/.config/waybar
ln -s ~/.dotfiles/arch/.gtkrc-2.0 ~/.gtkrc-2.0
ln -s ~/.dotfiles/.gitconfig ~/.gitconfig
