format = """
[░▒▓](#DB4740)\
[ 侍 ](bold bg:#DB4740 fg:#090c0c)\
[](bg:#0F120F fg:#DB4740)\
$directory\
[](fg:#0F120F bg:#E0CDA5)\
$git_branch\
$git_status\
[](fg:#E0CDA5)\
$nodejs\
$rust\
$golang\
$php\
\n$character"""

[character]
success_symbol = '[](bold #E0CDA5) '
error_symbol = '[󰞇](bold red) '

[directory]
style = "bold fg:#DB4740 bg:#0F120F"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](bold fg:#0F120F bg:#E0CDA5)]($style)'

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](bold fg:#DB4740 bg:#E0CDA5)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
