require "kenshin.options"
require "kenshin.keymaps"
require "kenshin.plugins"
require "kenshin.colorscheme"
require "kenshin.cmp"
require "kenshin.lsp"
require "kenshin.telescope"
require "kenshin.treesitter"
require "kenshin.gitsigns"
require "kenshin.dap"
require "kenshin.statusline"
require "kenshin.noice"
require "kenshin.autopairs"
-- require "kenshin.jacoco"
